//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy
    {
        public int BuyId { get; set; }
        public int PackagePackageId { get; set; }
        public int SellSellId { get; set; }
        public int CustomerCustomerId { get; set; }
        public string Name { get; set; }
    
        public virtual Sell Sell { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
