//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Winnary> WinnarySet { get; set; }
        public virtual DbSet<City> CitySet { get; set; }
        public virtual DbSet<Vine> VineSet { get; set; }
        public virtual DbSet<Employees> EmployeesSet1 { get; set; }
        public virtual DbSet<Storehouse> StorehouseSet { get; set; }
        public virtual DbSet<Transport> TransportSet { get; set; }
        public virtual DbSet<Package> PackageSet { get; set; }
        public virtual DbSet<Sell> SellSet { get; set; }
        public virtual DbSet<Customer> CustomerSet { get; set; }
        public virtual DbSet<Buy> BuySet { get; set; }
        public virtual DbSet<Taster> TasterSet { get; set; }
        public virtual DbSet<Tasting> TastingSet { get; set; }
        public virtual DbSet<Champagne> ChampagneSet { get; set; }
        public virtual DbSet<TastingChampagne> TastingChampagneSet { get; set; }
        public virtual DbSet<Hierarchy> HierarchySet { get; set; }
    }
}
