//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TastingChampagne
    {
        public int TastingChampagneId { get; set; }
        public int ChampagneChampagneId { get; set; }
        public int TastingTastingId { get; set; }
    
        public virtual Champagne Champagne { get; set; }
        public virtual Tasting Tasting { get; set; }
    }
}
