//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tasting()
        {
            this.TastingChampagne = new HashSet<TastingChampagne>();
        }
    
        public int TastingId { get; set; }
        public int TasterTasterId { get; set; }
        public int WhiteVineVineId { get; set; }
    
        public virtual Taster Taster { get; set; }
        public virtual WhiteVine WhiteVine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TastingChampagne> TastingChampagne { get; set; }
    }
}
